safe:        false
port:        4000

source:      .
destination: ./_site

future:      true
lsi:         false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

baseurl:        http://jennerhanni.net/advent-of-code

title:       Advent of Code Solutions
description: Brute force python everywhere!
author:      Jenner Hanni
email:       jeh.wicker@gmail.com

exclude:     [drafts, _site, scripts]

